### ISSUE TITLE
Getting Metamask errors when sending tx

### ISSUE THREAD

**Issue by molekilla** [opengsn/gsn#420]
Any idea?

```
error, body {RelayServerAddress: "0x421506fa2e12b5669b7f994f264fb61694557ef6", RelayManagerAddress: "0x2e38199af91d80639a6ce2f1a8c7cadba38a0580", RelayHubAddress: "0xEF46DD512bCD36619a6531Ca84B188b47D85124b", MinGasPrice: "1100000000", Ready: true, …}
RelayClient.js?ec70:256 on-chain forwarder for: 0x565D5b81C8e2158d528a074E9d6672c6e1faE54c is 0xcC87aa60a6457D9606995C4E7E9c38A2b627Da88
inpage.js:1 MetaMask - RPC Error: Data must be passed as a valid JSON string. {code: -32603, message: "Data must be passed as a valid JSON string.", data: {…}, stack: "AssertionError: Data must be passed as a valid JSO…eogaeaoehlefnkodbefgpgknn/background.js:1:1225775"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
Management.vue?22c0:89 Error: Rejected relayTransaction call - should not happen. Reason: {"code":-32603,"message":"Data must be passed as a valid JSON string.","data":{"originalError":{"name":"AssertionError","actual":"object","expected":"string","operator":"==","message":"Data must be passed as a valid JSON string.","generatedMessage":false}},"stack":"AssertionError: Data must be passed as a valid JSON string.\n    at t.exports.validateParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:114970)\n    at t.exports.addUnapprovedMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:114040)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:113597\n    at new Promise (<anonymous>)\n    at t.exports.addUnapprovedMessageAsync (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:113564)\n    at t.exports.newUnsignedTypedMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:140720)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1225775"}
    at eval (RelayProvider.js?57e8:107)
```

**Comment by molekilla** [comment]
without methodSuffix set:

```
Error: Rejected relayTransaction call - should not happen. Reason: {"code":-32603,"message":"e.toLowerCase is not a function","data":{"originalError":{}},"stack":"TypeError: e.toLowerCase is not a function\n    at m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1227129)\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1224948"}
```

**Comment by drortirosh** [comment]
Try to add to the GSN config `jsonStringifyRequest:true`, methodSuffix:'_v4'

**Comment by molekilla** [comment]
great, that work. But I get a signing error in the 2nd metamask signing request.  First test used a naive paymaster impl, same. Then used a sample code from Metacoin with HashcashPaymaster.sol from gsn contracts repo, and get the same issue.

https://gist.github.com/molekilla/5bc840d5b95a4ef95b8f980440e42424

**Comment by molekilla** [comment]
@drortirosh Any idea? If is something with HashcashPaymaster I'm using or the ropsten relayer? Thanks

**Comment by drortirosh** [comment]
Use opengsn/gsn@0.9, not the latest 0.10 (because that's what is currently deployed to kovan,ropsten)
