### ISSUE TITLE
VM Exception while processing transaction: invalid opcode

### ISSUE THREAD

**Issue by willrnch** [opengsn/gsn#523]
When running `gsn start` (`npx gsn start` or `node ./dist/src/cli/commands/gsn.js start`), I get the following error:

```
Error: Returned error: VM Exception while processing transaction: invalid opcode
    at Object.ErrorResponse (/github.com/opengsn/gsn/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /github.com/opengsn/gsn/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/github.com/opengsn/gsn/node_modules/web3-providers-http/src/index.js:110:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/github.com/opengsn/gsn/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/github.com/opengsn/gsn/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/github.com/opengsn/gsn/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/github.com/opengsn/gsn/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I run the command with `-n http://127.0.0.1:7545` and I have Ganache 2.5.4.1367 behind `http://127.0.0.1:7545`.
node is v12.18.4.

**Comment by willrnch** [comment]
It works with `Ganache CLI v6.12.1 (ganache-core: 2.13.1)`.
