### ISSUE TITLE
Invalid JSON RPC response when initialazing RelayProvider

### ISSUE THREAD

**Issue by ragalz** [opengsn/gsn#630]
Hello, I've been trying to use GSN with rinkeby and Infura, and seems like the RelayProvider is unable to connect to Infura. I've run the same code on local (slightly different) and it works just fine.

Here is my code: 

```
// Deploy Paymaster contract
  console.log("Account balance:", (await deployer.getBalance()).toString());
  const Paymaster = await ethers.getContractFactory("AcceptEverythingPaymaster");
  const paymaster = await Paymaster.deploy();
  
  await paymaster.deployed();
  console.log("Paymaster deployed to:", paymaster.address);
  
  
  // const web3provider = new Web3HttpProvider("http://localhost:8545")
  const web3provider = new Web3HttpProvider("https://rinkeby.infura.io/v3/6c398496bdbc42b2a55651d8501f181c")
  const deploymentProvider = new ethers.providers.Web3Provider(web3provider)
  // const deploymentProvider = new ethers.providers.InfuraProvider("rinkeby", "6c398496bdbc42b2a55651d8501f181c");
  console.log("Deployment Provider instanced!");

  const gsnConfig = {
    paymasterAddress: paymaster.address,
    loggerConfiguration: {
      logLevel: 'debug',
    }
  }
  const gsnProvider = RelayProvider.newProvider({
    provider: deploymentProvider, config: gsnConfig
  });
  console.log("GSN Provider instanced!");
  await gsnProvider.init(); // THIS LINE IS THROWING AN ERROR
  console.log("GSN Provider initialized!");
  
  // Set everything up
  console.log("Setting forwarder address on token contract...");
  await token.setForwarder(FORWARDER_ADDRESS);
```

And the error is as follows:

```
(node:24869) UnhandledPromiseRejectionWarning: Error: invalid json request
    at /home/rafa/Dev/tcsmartcontracts/node_modules/@ethersproject/providers/src.ts/web3-provider.ts:51:35
    at XMLHttpRequest.request.onreadystatechange (/home/rafa/Dev/tcsmartcontracts/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24869) UnhandledPromiseRejectionWarning: Error: invalid json request
    at /home/rafa/Dev/tcsmartcontracts/node_modules/@ethersproject/providers/src.ts/web3-provider.ts:51:35
    at XMLHttpRequest.request.onreadystatechange (/home/rafa/Dev/tcsmartcontracts/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:24869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24869) UnhandledPromiseRejectionWarning: Error: invalid json request
    at /home/rafa/Dev/tcsmartcontracts/node_modules/@ethersproject/providers/src.ts/web3-provider.ts:51:35
    at XMLHttpRequest.request.onreadystatechange (/home/rafa/Dev/tcsmartcontracts/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/home/rafa/Dev/tcsmartcontracts/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:24869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by drortirosh** [comment]
sorry for the late response...
GSN currently can't wrap ethers provider, only an RPC provider (aka web3 provider)
note that `ethers.provider.Web3Provider` is a misnomer: its a WRAPPER for a **web3** provider, which yields an **ethers** provider.

it should work if you pass GSN your web3provider, and then do
```
etherProvider =  new ethers.providers.Web3Provider(gsn3provider)
```
