### ISSUE TITLE
Document new network deployment.

### ISSUE THREAD

**Issue by drortirosh** [opengsn/gsn#72]
Document how to:

- Deploy new RelayHub
- Save its address
- Configure and deploy relay(s) to use the new hub
- Configure dApp to use the new relay.

**Comment by crossoveranx** [comment]
Has this been documented anywhere? I would like to deply the gas station network to a private chain but it seems the documentation is unclear on how to get this started.

**Comment by drortirosh** [comment]
There isn't a proper RelayHub deployment document yet.
Run: `scripts/singleton/compute.sh` to generate deployment artifacts
And then `scripts/singleton/deploy.js` to deploy it.

To deploy a relay, use  https://github.com/tabookey/tabookey-gasless/blob/master/docs/relay-deployment.md

**Comment by crossoveranx** [comment]
Unfortunately, this doesn't work for me. I have successfully deployed the Relay Hub contract to my private net and have set up the HttpServer. However, when doing the last step, you linked in the deploy relay regarding funding from a local workstation, I receive an error.

I run the fundrelay.js file with the appropriate parameters. I then receive this error:

```
staking  1100000000000000000
(node:32660) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xdb057750d77da3477fe232c26402127ce9fa298b079596964b03dabda867c0df",
  "blockNumber": 3892460,
  "contractAddress": null,
  "cumulativeGasUsed": 8000000,
  "from": "0xd748bf41264b906093460923169643f45bdbc32e",
  "gasUsed": 8000000,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "root": null,
  "status": false,
  "to": "0xd216153c06e857cd7f72665e0af1d7d82172f494",
  "transactionHash": "0xb191e6e0bd12167af23caa6e072dfcab7b4b4cbb3526ce29a823c0c8a4d60240",
  "transactionIndex": 0,
  "events": {}
}
    at /home/james/tabookey-gasless/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:412:37
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:32660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:32660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas on what I could try?
