### ISSUE TITLE
CLI does not consistently invoke CommandLogic.init()

### ISSUE THREAD

**Issue by james-mathiesen** [opengsn/gsn#835]
ContractInteractor defers certain initialization to an init() method.

CommandLogic defers certain initialization to an init() method (which also invokes ContractInteractor's init)

Only `gsn status` explicitly invokes CommandLogic's init() method

This means that other GSN commands (at least paymaster-balancer and paymaster-fund) consistently fail because ContractInteractor is only partially initialized.

```
TypeError: Cannot read property 'balanceOf' of undefined
    at ContractInteractor.hubBalanceOf (/Users/jmathiesen/.nvm/versions/node/v13.14.0/lib/node_modules/@opengsn/cli/node_modules/@opengsn/common/src/ContractInteractor.ts:665:40)
    at CommandsLogic.getPaymasterBalance (/Users/jmathiesen/.nvm/versions/node/v13.14.0/lib/node_modules/@opengsn/cli/src/CommandsLogic.ts:156:42)
    at /Users/jmathiesen/.nvm/versions/node/v13.14.0/lib/node_modules/@opengsn/cli/src/commands/gsn-paymaster-balance.ts:24:31
    at Object.<anonymous> (/Users/jmathiesen/.nvm/versions/node/v13.14.0/lib/node_modules/@opengsn/cli/src/commands/gsn-paymaster-balance.ts:26:3)
```

**Comment by dahof1** [comment]
I experienced that behavior also with other commands like `relayer-register`

**Comment by drortirosh** [comment]
tested and `paymaster-fund` works (even though it is rarely used, as it is simpler to send funds directly to paymaster)
`relayer-register` works (as it is used extensively, to register relayers)
